CREATE TABLE solicitudes(
	id INT AUTO_INCREMENT PRIMARY KEY,
	org_name VARCHAR(50),
	org_rut VARCHAR(15),
	org_address VARCHAR(50),	
	org_email VARCHAR(50),
	org_phone INT,
	org_type VARCHAR(50),
	owner_name VARCHAR(50),
	owner_rut VARCHAR(15),
	owner_address VARCHAR(50),	
	owner_email VARCHAR(50),
	owner_phone INT,
	owner_phone2 INT,
	activity_name VARCHAR(50),
	place VARCHAR(50),
	start_date VARCHAR(12),
	start_time VARCHAR(12),
	end_date VARCHAR(12),
	end_time VARCHAR(12),
	is_alcohol VARCHAR(4),
	is_food VARCHAR(4),
	description VARCHAR(250),
	purpose VARCHAR(250),
	docs VARCHAR(250)
);