POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "username": "emilio",
    "password": "emilio123"
}
###
POST http://localhost:4000/api/permisos/generar-decreto
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVtaWxpbyIsImlhdCI6MTcyOTEwMzM3NSwiZXhwIjoxNzI5MTA2OTc1fQ.YWG-3vinaDxXF_VwgEPgcezSfq9FcgVAiljZtKn6s1E

{
    "org_name": "Caipirinho",
    "start_date": "2024-09-09",
}

###
GET http://localhost:4000/api/organizaciones
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVtaWxpbyIsImlhdCI6MTcyODkxOTU3MSwiZXhwIjoxNzI4OTIzMTcxfQ.grAXmmWFNyibNnPubgIf5RQE9A3Nm9tx8uEvKWJfCv4

###

###
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "username": "emilio",
    "password": "emilio123"
}
###
POST http://localhost:4000/api/email/send-email
Content-Type: application/json

{
    "to": "emiliosotoandrade256@gmail.com",
    "subject": "Prueba de nodemailer",
    "html": "<h1>Correo enviado exitosamente</h1>"
}
###
PATCH http://localhost:4000/api/documentos/1
###
GET http://localhost:4000/api/organizaciones/1
###
GET http://localhost:4000/api/documentos/2
###
POST http://localhost:4000/api/documentos/1
Content-Type: application/json

[
    {
    "fieldname": "orgFile",
    "originalname": "comida.jpg",
    "filename": "0004448889997777KKKK",
    "path": "uploads\\0004448889997777KKKK.jpg"
},
{
    "fieldname": "orgFile",
    "originalname": "comida2.jpg",
    "filename": "0004448889997777KKKK2",
    "path": "uploads\\0004448889997777KKKK2.jpg"
}
]
###
GET http://localhost:4000/api/solicitudes?filters=rechazada&filters=pendiente
###
POST http://localhost:4000/api/solicitudes
Content-Type: application/json
{
    "org_name": "Kamehameh"
}
###
PATCH http://localhost:4000/api/solicitudes/3
Content-Type: application/json
{
    "status": "aprobada"
}
###
GET http://localhost:4000/api/organizaciones/1/documents
###
POST http://localhost:4000/api/organizaciones
Content-Type: application/json
{
    "org_name": "Junta de vecinos de Chonchi",
    "org_rut": "77.722.230-2",
    "org_address": "Calle 123",
    "org_email": "correo@gmail.com",
    "org_phone": "+569 4873948",
    "org_type": "Junta de Vecinos",
    "name": "Emilio Soto B",
    "rut": "19.722.280-8",
    "address": "Sargento Candelaria 3821",
    "email": "correo@gmail.com",
    "phone": "+569 84932093",
}
###
PATCH http://localhost:4000/api/organizaciones/17/
Content-Type: application/json
{
    "org_name": "Prueba 17"
}
###
GET http://localhost:4000/api/presidentes?organizationId=1
###
POST http://localhost:4000/api/presidentes
Content-Type: application/json
{
    "name": "Emilio Soto B",
    "rut": "19.722.280-8",
    "address": "Sargento Candelaria 3821",
    "email": "correo@gmail.com",
    "phone": "+569 84932093",
}
###
GET http://localhost:4000/api/permisos?organizationId=4
###
GET http://localhost:4000/api/permisos/1
###
POST http://localhost:4000/api/permisos
Content-Type: application/json
{
    "activity_name": "Bingo bailable 666",
    "place": "Gimnasio Municipal",
    "start_date": "2024-02-02",
    "start_time": "13:00",
    "end_date": "2024-02-03",
    "end_time": "14:00",
    "is_alcohol": 1,
    "is_food": 0,
    "description": "Breve descripción de la actividad",
    "purpose": "Destino de los fondos recaudados",
    "organizationId": 5
}
###
PATCH http://localhost:4000/api/permisos/4
Content-Type: application/json
{
    "place": "Miami"
}